### ISSUE TITLE
WPA Enterprise

### ISSUE THREAD

**Issue by ski7777** [theojulienne/go-wireless#14]
Hello,

is it possible to use WPA2 Enterprise with this lib? If yes, how? A code example would be nice. If no, what do I need to change?

Raphael

**Comment by penguinpowernz** [comment]
Hey I'm not sure, I've never use WPA enterprise before. How is it different?

I'm sure it would be supported as we can do anything that WPA CLI supports, it would just be about seeing if the current syntactic sugar wrapper would support it, otherwise making it support that or adding some more syntactic sugar.

**Comment by penguinpowernz** [comment]
Closing due to no reply, assume WPA enterprise works with this, ni way to test this on my end.
